# Generated by Django 6.1.1 on 2026-09-24 16:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код ачивки')),
                ('title', models.CharField(max_length=150, verbose_name='Название достижения')),
                ('description', models.TextField(verbose_name='Условие получения')),
                ('icon_name', models.CharField(default='award', max_length=50, verbose_name='Иконка')),
                ('badge_color', models.CharField(default='#082a99', max_length=30, verbose_name='Цвет плашки')),
                ('xp_reward', models.PositiveIntegerField(default=200, verbose_name='Награда (XP)')),
                ('rarity', models.CharField(choices=[('common', 'Обычное'), ('rare', 'Редкое'), ('epic', 'Эпическое'), ('legendary', 'Легендарное')], default='rare', max_length=30, verbose_name='Редкость')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код компетенции')),
                ('title', models.CharField(max_length=150, verbose_name='Название компетенции')),
                ('description', models.TextField(verbose_name='Описание компетенции')),
                ('icon', models.CharField(default='award', max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='#1c6389', max_length=30, verbose_name='Фирменный цвет')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название сценария')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-слаг')),
                ('category', models.CharField(choices=[('conflict', 'Конфликт и претензии пассажиров'), ('medical', 'Медицинский инцидент и первая помощь'), ('safety', 'Пожарная тревога и безопасность'), ('anti_terror', 'Антитеррористический регламент'), ('tech_failure', 'Технический сбой и климат'), ('vip_service', 'Премиальный VIP-сервис 400 км/ч')], default='conflict', max_length=50, verbose_name='Категория')),
                ('difficulty', models.CharField(choices=[('easy', 'Базовый (Стандарт)'), ('medium', 'Повышенный (Бизнес)'), ('hard', 'Стрессовый (400 км/ч)'), ('extreme', 'Критический инцидент')], default='medium', max_length=30, verbose_name='Сложность')),
                ('train_speed', models.PositiveIntegerField(default=360, verbose_name='Скорость поезда (км/ч)')),
                ('train_number', models.CharField(default='№ 702 «Белый кречет» Москва — Санкт-Петербург', max_length=50, verbose_name='Поезд')),
                ('location_name', models.CharField(default='Перегон Новая Тверь — Логовежь, 218 км', max_length=150, verbose_name='Локация перегона')),
                ('car_info', models.CharField(default='Вагон № 2 (Бизнес-класс)', max_length=150, verbose_name='Класс вагона')),
                ('description', models.TextField(verbose_name='Краткое описание вводной')),
                ('briefing', models.TextField(verbose_name='Подробный вводный инструктаж')),
                ('regulation_reference', models.TextField(verbose_name='Нормативный регламент / Ссылка на стандарты ВСМ')),
                ('background_image', models.CharField(default='train_interior_1.png', max_length=100, verbose_name='Фоновое изображение')),
                ('base_xp', models.PositiveIntegerField(default=250, verbose_name='Базовый XP за прохождение')),
                ('time_limit_default', models.PositiveIntegerField(default=30, verbose_name='Таймер по умолчанию (сек)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConductorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(default='VSM-0402', max_length=30, verbose_name='Табельный номер')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО сотрудника')),
                ('depot', models.CharField(default='Москва-Октябрьская ВСМ (Северо-Западная дирекция)', max_length=150, verbose_name='Депо приписки')),
                ('rank', models.CharField(choices=[('trainee', 'Стажер-проводник ВСМ'), ('conductor', 'Проводник ВСМ 2 класса'), ('senior_conductor', 'Старший стюард ВСМ 1 класса'), ('instructor', 'Инструктор поездных бригад ВСМ'), ('master', 'Мастер высокоскоростного сервиса')], default='conductor', max_length=50, verbose_name='Квалификационный ранг')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень')),
                ('experience_points', models.PositiveIntegerField(default=350, verbose_name='Очки опыта (XP)')),
                ('loyalty_rating', models.FloatField(default=88.5, verbose_name='Рейтинг лояльности (%)')),
                ('safety_rating', models.FloatField(default=96.0, verbose_name='Рейтинг безопасности (%)')),
                ('service_rating', models.FloatField(default=90.0, verbose_name='Рейтинг сервиса (%)')),
                ('shifts_completed', models.PositiveIntegerField(default=5, verbose_name='Завершенных смен / ситуаций')),
                ('perfect_shifts', models.PositiveIntegerField(default=3, verbose_name='Безупречных смен')),
                ('avatar', models.CharField(default='avatar_male.png', max_length=100, verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conductor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль проводника',
                'verbose_name_plural': 'Профили проводников',
            },
        ),
        migrations.CreateModel(
            name='ScenarioNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.CharField(max_length=50, verbose_name='Ключ узла (например, start)')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок этапа')),
                ('character_name', models.CharField(default='Пассажир', max_length=100, verbose_name='Имя субъекта')),
                ('character_role', models.CharField(default='Пассажир бизнес-класса', max_length=100, verbose_name='Роль субъекта')),
                ('character_mood', models.CharField(choices=[('calm', 'Спокойное'), ('irritated', 'Раздраженное / Агрессивное'), ('panicked', 'Паника / Испуг'), ('critical', 'Критическое состояние здоровья'), ('formal', 'Деловое / Протокольное')], default='irritated', max_length=50, verbose_name='Состояние / Тон')),
                ('dialogue_text', models.TextField(verbose_name='Реплика пассажира / Сообщение системы')),
                ('narrative_context', models.TextField(blank=True, verbose_name='Оперативная обстановка (пульт, датчики, салон)')),
                ('time_limit_seconds', models.PositiveIntegerField(default=25, verbose_name='Лимит времени на решение (сек)')),
                ('is_terminal', models.BooleanField(default=False, verbose_name='Финальный узел (конец сценария)')),
                ('is_success', models.BooleanField(default=False, verbose_name='Успешный финал')),
                ('resolution_report', models.TextField(blank=True, verbose_name='Экспертный разбор действий и ошибок')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='simulator.scenario')),
            ],
            options={
                'verbose_name': 'Узел сценария',
                'verbose_name_plural': 'Узлы сценариев',
                'unique_together': {('scenario', 'node_key')},
            },
        ),
        migrations.CreateModel(
            name='ScenarioChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=350, verbose_name='Действие проводника / Реплика')),
                ('tactical_hint', models.CharField(blank=True, max_length=250, verbose_name='Тактическая мысль / Регламентная логика')),
                ('next_node_key', models.CharField(max_length=50, verbose_name='Ключ следующего узла')),
                ('loyalty_impact', models.IntegerField(default=0, verbose_name='Изменение лояльности')),
                ('safety_impact', models.IntegerField(default=0, verbose_name='Изменение безопасности')),
                ('service_impact', models.IntegerField(default=0, verbose_name='Изменение качества сервиса')),
                ('stress_impact', models.IntegerField(default=5, verbose_name='Изменение стресса (+ / -)')),
                ('competency_points', models.IntegerField(default=10, verbose_name='Очки компетенции')),
                ('feedback_toast', models.CharField(blank=True, max_length=300, verbose_name='Моментальная обратная связь')),
                ('audio_cue', models.CharField(choices=[('neutral', 'Обычный тон (Клик)'), ('success', 'Успешное действие (Сигнал согласия)'), ('warning', 'Предупреждение (Внимание)'), ('emergency', 'Тревога (Критическая ошибка)')], default='neutral', max_length=30, verbose_name='Звуковой отклик')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulator.competency', verbose_name='Компетенция')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='simulator.scenarionode')),
            ],
            options={
                'verbose_name': 'Вариант выбора проводника',
                'verbose_name_plural': 'Варианты выбора проводника',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_loyalty', models.IntegerField(default=75, verbose_name='Лояльность (%)')),
                ('current_safety', models.IntegerField(default=95, verbose_name='Безопасность (%)')),
                ('current_service', models.IntegerField(default=80, verbose_name='Качество сервиса (%)')),
                ('current_stress', models.IntegerField(default=20, verbose_name='Уровень стресса (%)')),
                ('elapsed_seconds', models.PositiveIntegerField(default=0, verbose_name='Затрачено секунд')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе прохождения'), ('completed', 'Успешно завершен'), ('failed', 'Провален (нарушение регламента ВСМ)'), ('timeout', 'Провален по таймеру')], default='in_progress', max_length=30, verbose_name='Статус сессии')),
                ('is_success', models.BooleanField(default=False, verbose_name='Успешный итог')),
                ('final_score', models.IntegerField(default=0, verbose_name='Итоговый счет')),
                ('earned_xp', models.IntegerField(default=0, verbose_name='Заработанный XP')),
                ('session_log', models.JSONField(default=list, verbose_name='Лог принятых решений')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='simulator.conductorprofile')),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulator.scenarionode')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='simulator.scenario')),
            ],
            options={
                'verbose_name': 'Обучающая сессия',
                'verbose_name_plural': 'Обучающие сессии',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ConductorCompetencyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=50, verbose_name='Уровень развития (0-100)')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.competency')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='simulator.conductorprofile')),
            ],
            options={
                'verbose_name': 'Оценка компетенции',
                'verbose_name_plural': 'Оценки компетенций',
                'unique_together': {('profile', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='ConductorAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Разблокировано')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.achievement')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='simulator.conductorprofile')),
            ],
            options={
                'verbose_name': 'Полученное достижение',
                'verbose_name_plural': 'Полученные достижения',
                'unique_together': {('profile', 'achievement')},
            },
        ),
    ]
