# Generated by Django 6.1.1 on 2026-09-24 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndlessChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код задачи')),
                ('title', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('category', models.CharField(default='service', max_length=50, verbose_name='Категория')),
                ('difficulty_level', models.PositiveIntegerField(choices=[(1, 'Уровень 1: Штатный сервис (250 км/ч)'), (2, 'Уровень 2: Напряженная посадка (300 км/ч)'), (3, 'Уровень 3: Конфликты и сбои (350 км/ч)'), (4, 'Уровень 4: Высокий стресс (380 км/ч)'), (5, 'Уровень 5: Критический экстрим (400 км/ч)')], default=1, verbose_name='Уровень сложности')),
                ('train_speed', models.PositiveIntegerField(default=300, verbose_name='Скорость (км/ч)')),
                ('car_info', models.CharField(default='Вагон № 3 (Комфорт)', max_length=100, verbose_name='Вагон')),
                ('character_name', models.CharField(default='Пассажир', max_length=100, verbose_name='Имя субъекта')),
                ('character_role', models.CharField(default='Пассажир', max_length=100, verbose_name='Роль')),
                ('character_mood', models.CharField(default='neutral', max_length=50, verbose_name='Тон/Настроение')),
                ('situation_text', models.TextField(verbose_name='Описание ситуации на борту')),
                ('dialogue_text', models.TextField(blank=True, verbose_name='Реплика персонажа / Вызов системы')),
                ('timer_seconds', models.PositiveIntegerField(default=20, verbose_name='Таймер на решение (сек)')),
                ('regulation_reference', models.TextField(verbose_name='Пункт правил / Регламент ВСМ')),
                ('competency_code', models.CharField(default='service_etiquette', max_length=50, verbose_name='Код ключевой компетенции')),
                ('choices_data', models.JSONField(default=list, verbose_name='Варианты решений')),
            ],
            options={
                'verbose_name': 'Задача бесконечной карусели',
                'verbose_name_plural': 'Задачи бесконечной карусели',
                'ordering': ['difficulty_level', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EndlessShiftSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Текущая серия верных решений')),
                ('max_streak', models.PositiveIntegerField(default=0, verbose_name='Максимальный стрик (рекорд)')),
                ('challenges_solved', models.PositiveIntegerField(default=0, verbose_name='Решено ситуаций')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='Суммарный счет')),
                ('earned_xp', models.PositiveIntegerField(default=0, verbose_name='Заработанный XP')),
                ('current_speed', models.PositiveIntegerField(default=260, verbose_name='Текущая скорость поезда')),
                ('current_loyalty', models.IntegerField(default=85, verbose_name='Лояльность (%)')),
                ('current_safety', models.IntegerField(default=95, verbose_name='Безопасность (%)')),
                ('current_service', models.IntegerField(default=85, verbose_name='Сервис (%)')),
                ('current_stress', models.IntegerField(default=15, verbose_name='Стресс (%)')),
                ('status', models.CharField(choices=[('active', 'На линии (активна)'), ('completed', 'Смена сдана (успешно)'), ('failed', 'Сход с линии (провал лояльности/безопасности)')], default='active', max_length=30, verbose_name='Статус смены')),
                ('solved_challenge_ids', models.JSONField(default=list, verbose_name='ID решенных задач')),
                ('history_log', models.JSONField(default=list, verbose_name='История решений смены')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endless_sessions', to='simulator.conductorprofile')),
            ],
            options={
                'verbose_name': 'Сессия бесконечной смены',
                'verbose_name_plural': 'Сессии бесконечных смен',
                'ordering': ['-started_at'],
            },
        ),
    ]
