# Generated by Django 6.1.1 on 2026-09-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_endlesschallenge_endlessshiftsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductorprofile',
            name='is_example',
            field=models.BooleanField(default=False, verbose_name='Тестовый аккаунт для примера'),
        ),
        migrations.AlterField(
            model_name='conductorprofile',
            name='avatar',
            field=models.CharField(default='avatar_1.svg', max_length=100, verbose_name='Аватар'),
        ),
    ]
