# Generated by Django 6.1.1 on 2026-09-24 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_conductorprofile_is_example_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endlesschallenge',
            name='source_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carousel_challenges', to='simulator.scenario', verbose_name='Связанный сценарий'),
        ),
        migrations.AddField(
            model_name='endlesschallenge',
            name='source_type',
            field=models.CharField(choices=[('carousel', 'Задача карусели'), ('scenario', 'Из сценария ВСМ')], default='carousel', max_length=30, verbose_name='Источник задачи'),
        ),
        migrations.AddField(
            model_name='endlessshiftsession',
            name='is_perfect',
            field=models.BooleanField(default=True, verbose_name='Безупречная смена'),
        ),
        migrations.AddField(
            model_name='endlessshiftsession',
            name='mistakes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество ошибок'),
        ),
        migrations.AddField(
            model_name='endlessshiftsession',
            name='shift_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер смены'),
        ),
        migrations.AddField(
            model_name='endlessshiftsession',
            name='target_challenges_count',
            field=models.PositiveIntegerField(default=8, verbose_name='План смены (рейс)'),
        ),
    ]
