# Generated by Django 6.1.1 on 2026-09-25 07:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_endlesschallenge_source_scenario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True, verbose_name='Уникальный ключ документа')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок / Номер распоряжения')),
                ('order_number', models.CharField(blank=True, max_length=100, verbose_name='Номер распоряжения ВСМ')),
                ('category', models.CharField(default='standard', max_length=50, verbose_name='Категория регламента')),
                ('badge', models.CharField(default='Стандарт ВСМ', max_length=100, verbose_name='Текст плашки')),
                ('badge_color', models.CharField(default='#082a99', max_length=30, verbose_name='Цвет плашки')),
                ('icon', models.CharField(default='book-open', max_length=50, verbose_name='Иконка')),
                ('description', models.TextField(verbose_name='Аннотация и назначение')),
                ('content_markdown', models.TextField(verbose_name='Структурированный текст регламента')),
                ('chapters_data', models.JSONField(default=list, verbose_name='Список глав и разделов')),
                ('file_base64', models.TextField(blank=True, verbose_name='Base64 бинарного PDF файла')),
                ('file_name', models.CharField(default='document.pdf', max_length=150, verbose_name='Имя файла для скачивания')),
                ('file_size_display', models.CharField(default='150 КБ', max_length=50, verbose_name='Отображаемый размер')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Нормативный документ (БД)',
                'verbose_name_plural': 'Нормативные документы (БД)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='conductorprofile',
            name='brigade',
            field=models.CharField(default='Поездная бригада № 1', max_length=50, verbose_name='Поездная бригада'),
        ),
        migrations.AddField(
            model_name='scenarionode',
            name='timeout_next_node_key',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Узел при истечении времени'),
        ),
        migrations.AddField(
            model_name='scenarionode',
            name='timeout_penalty',
            field=models.IntegerField(default=15, verbose_name='Штраф при таймауте'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='debrief_feedback',
            field=models.JSONField(blank=True, default=dict, verbose_name='Обучающий экспертный разбор'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст оповещения')),
                ('notification_type', models.CharField(choices=[('scenario', 'Новый сценарий'), ('challenge', 'Скоростной челлендж'), ('points_expiring', 'Сгорающие баллы'), ('achievement', 'Новое достижение'), ('system', 'Системное оповещение')], default='system', max_length=50, verbose_name='Тип')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка для перехода')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время получения')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='simulator.conductorprofile')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
