# Generated by Django 6.1.1 on 2026-09-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_regulationdocument_conductorprofile_brigade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductorprofile',
            name='crew_members',
            field=models.ManyToManyField(blank=True, to='simulator.conductorprofile', verbose_name='Члены поездного экипажа (коллеги/друзья)'),
        ),
    ]
