# Generated by Django 6.1.1 on 2026-09-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_conductorprofile_crew_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductorprofile',
            name='training_track',
            field=models.CharField(choices=[('all', 'Универсальная подготовка (Все классы)'), ('economy', 'Проводник Эконом-класса (Стандарт)'), ('comfort', 'Проводник Комфорт-класса'), ('business', 'Стюард Бизнес и Первого класса')], default='all', max_length=30, verbose_name='Специализация обучения'),
        ),
        migrations.AddField(
            model_name='endlesschallenge',
            name='service_class',
            field=models.CharField(choices=[('economy', 'Эконом-класс (Стандарт)'), ('comfort', 'Комфорт-класс'), ('business', 'Бизнес и Первый класс'), ('all', 'Общепоездной регламент / ПТЭ')], default='all', max_length=30, verbose_name='Класс обслуживания'),
        ),
        migrations.AddField(
            model_name='endlessshiftsession',
            name='service_class',
            field=models.CharField(choices=[('all', 'Смешанный рейс ВСМ-1 (Все классы)'), ('economy', 'Смена в Эконом-классе (Стандарт)'), ('comfort', 'Смена в Комфорт-классе'), ('business', 'Смена в Бизнес и Первом классе')], default='all', max_length=30, verbose_name='Класс вагона смены'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='service_class',
            field=models.CharField(choices=[('economy', 'Эконом-класс (Стандарт)'), ('comfort', 'Комфорт-класс'), ('business', 'Бизнес и Первый класс'), ('all', 'Общепоездной регламент / ПТЭ')], default='all', max_length=30, verbose_name='Класс обслуживания'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='background_image',
            field=models.CharField(default='vsm_train_exterior.jpg', max_length=100, verbose_name='Фоновое изображение'),
        ),
    ]
