# Generated by Django 6.1.1 on 2026-09-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_conductorprofile_training_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductorprofile',
            name='sber_access_token',
            field=models.TextField(blank=True, default='', verbose_name='OAuth Access Token'),
        ),
        migrations.AddField(
            model_name='conductorprofile',
            name='sber_auth_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Личный ключ авторизации ИИ'),
        ),
        migrations.AddField(
            model_name='conductorprofile',
            name='sber_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Корпоративный ID сотрудника'),
        ),
        migrations.AddField(
            model_name='conductorprofile',
            name='sber_refresh_token',
            field=models.TextField(blank=True, default='', verbose_name='OAuth Refresh Token'),
        ),
        migrations.AddField(
            model_name='conductorprofile',
            name='sber_scope',
            field=models.CharField(blank=True, default='GIGACHAT_API_PERS', max_length=100, verbose_name='Scope авторизации'),
        ),
    ]
