# Generated by Django 6.1.1 on 2026-09-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0008_conductorprofile_sber_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductorprofile',
            name='salutespeech_auth_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ключ авторизации речевого сервиса (SALUTE_SPEECH_PERS)'),
        ),
    ]
