# Generated by Django 6.1.1 on 2026-09-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0009_conductorprofile_salutespeech_auth_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductorprofile',
            name='sber_client_id',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Client ID платформы ИИ'),
        ),
        migrations.AddField(
            model_name='conductorprofile',
            name='sber_client_secret',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Client Secret платформы ИИ'),
        ),
    ]
