from django.urls import path
from . import views

app_name = 'simulator'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('scenarios/', views.scenario_list, name='scenario_list'),
    path('scenario/<slug:slug>/', views.scenario_detail, name='scenario_detail'),
    path('scenario/<slug:slug>/start/', views.start_simulation, name='start_simulation'),
    path('simulation/<int:session_id>/', views.simulation_play, name='simulation_play'),
    path('simulation/<int:session_id>/result/', views.simulation_result, name='simulation_result'),
    path('api/simulation/<int:session_id>/choose/', views.api_choose_action, name='api_choose_action'),
    path('profile/', views.conductor_profile_view, name='profile'),
    path('profile/track/<str:track>/', views.set_training_track_web, name='set_training_track_web'),
    path('profile/reset/', views.reset_account_data, name='reset_account_data'),
    path('api/crew/add/<int:profile_id>/', views.api_crew_add, name='api_crew_add'),
    path('api/crew/remove/<int:profile_id>/', views.api_crew_remove, name='api_crew_remove'),
    path('leaderboard/', views.leaderboard_view, name='leaderboard'),
    path('analytics/', views.analytics_view, name='analytics'),
    path('regulations/', views.regulations_guide, name='regulations'),
    path('regulations/pdf/<str:doc_key>/', views.view_pdf_document, name='view_pdf_document'),
    path('regulations/download/<str:doc_key>/', views.download_document, name='download_document'),
    path('api/regulations/reader/<str:doc_key>/', views.api_document_reader, name='api_document_reader'),
    path('endless/', views.endless_carousel_view, name='endless_carousel'),
    path('api/endless/start/', views.api_start_endless_session, name='api_endless_start'),
    path('api/endless/<int:session_id>/choose/', views.api_endless_choose, name='api_endless_choose'),
    path('api/endless/<int:session_id>/finish/', views.api_endless_finish, name='api_endless_finish'),
    path('api/endless/<int:session_id>/state/', views.api_endless_state, name='api_endless_state'),
    path('switch-profile/<int:profile_id>/', views.switch_conductor_profile, name='switch_profile'),
    # Центр уведомлений
    path('api/notifications/', views.api_notifications_list, name='api_notifications_list'),
    path('api/notifications/<int:notification_id>/read/', views.api_notification_mark_read, name='api_notification_mark_read'),
    path('api/notifications/read-all/', views.api_notifications_read_all, name='api_notifications_read_all'),
    path('api/analytics/', views.api_analytics_data, name='api_analytics_data'),
    # REST API v1
    path('api/docs/', views.swagger_ui, name='swagger_ui'),
    path('api/v1/openapi.json', views.api_v1_openapi, name='api_v1_openapi'),
    path('api/v1/profile/', views.api_v1_profile, name='api_v1_profile'),
    path('api/v1/profile/training-track/', views.api_v1_set_training_track, name='api_v1_set_training_track'),
    path('api/v1/profile/reset/', views.api_v1_profile_reset, name='api_v1_profile_reset'),
    path('api/v1/crew/', views.api_v1_crew, name='api_v1_crew'),
    path('api/v1/crew/add/<int:profile_id>/', views.api_v1_crew_add, name='api_v1_crew_add'),
    path('api/v1/crew/remove/<int:profile_id>/', views.api_v1_crew_remove, name='api_v1_crew_remove'),
    path('api/v1/scenarios/', views.api_v1_scenarios, name='api_v1_scenarios'),
    path('api/v1/scenario/<slug:slug>/', views.api_v1_scenario_detail, name='api_v1_scenario_detail'),
    path('api/v1/simulation/start/<slug:slug>/', views.api_v1_simulation_start, name='api_v1_simulation_start'),
    path('api/v1/simulation/<int:session_id>/choose/', views.api_v1_simulation_choose, name='api_v1_simulation_choose'),
    path('api/v1/simulation/<int:session_id>/timeout/', views.api_v1_simulation_timeout, name='api_v1_simulation_timeout'),
    path('api/v1/simulation/<int:session_id>/debrief/', views.api_v1_simulation_debrief, name='api_v1_simulation_debrief'),
    path('api/v1/notifications/', views.api_v1_notifications, name='api_v1_notifications'),
    path('api/v1/analytics/', views.api_v1_analytics, name='api_v1_analytics'),
    path('api/v1/leaderboard/', views.api_v1_leaderboard, name='api_v1_leaderboard'),
    path('api/v1/regulations/', views.api_v1_regulations, name='api_v1_regulations'),
    path('api/v1/regulations/<str:doc_key>/', views.api_v1_regulation_detail, name='api_v1_regulation_detail'),
    # Скоростная карусель решений v1
    path('api/v1/carousel/start/', views.api_start_endless_session, name='api_v1_carousel_start'),
    path('api/v1/carousel/<int:session_id>/choose/', views.api_endless_choose, name='api_v1_carousel_choose'),
    path('api/v1/carousel/<int:session_id>/finish/', views.api_endless_finish, name='api_v1_carousel_finish'),
    path('api/v1/carousel/<int:session_id>/state/', views.api_endless_state, name='api_v1_carousel_state'),
    path('api/v1/tts/preload-list/', views.api_v1_tts_preload_list, name='api_v1_tts_preload_list'),
    path('api/v1/tts/', views.api_v1_tts, name='api_v1_tts'),
    # Live ИИ-диалог и речевой комплекс ВСМ
    path('api/v1/live/turn/', views.api_live_turn, name='api_live_turn'),
    path('api/v1/live/asr/', views.api_live_asr, name='api_live_asr'),
    path('api/v1/live/tts/', views.api_live_tts, name='api_live_tts'),
    path('api/v1/conductor/sber-credentials/', views.api_conductor_sber_credentials, name='api_conductor_sber_credentials'),
    path('api/v1/sber/verify-key/', views.api_verify_sber_key, name='api_verify_sber_key'),
    # Авторизация и регистрация проводников
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # Корпоративный ID OAuth 2.0
    path('auth/sber/', views.auth_sber_login, name='auth_sber_login'),
    path('auth/sber/callback/', views.auth_sber_callback, name='auth_sber_callback'),
    # Технические данные и SEO/PWA
    path('favicon.ico', views.favicon_ico, name='favicon_ico'),
    path('robots.txt', views.robots_txt, name='robots_txt'),
    path('sitemap.xml', views.sitemap_xml, name='sitemap_xml'),
    path('manifest.json', views.manifest_json, name='manifest_json'),
    path('sw.js', views.service_worker_js, name='service_worker_js'),
    path('humans.txt', views.humans_txt, name='humans_txt'),
]
